---
app_name: ninja-board
namespace: ninja-board
ninja_board_dev_namespace: "{{ namespace }}-dev"
ninja_board_prod_namespace: "{{ namespace }}"

source_repo: https://github.com/redhat-cop/ninja-board.git
source_ref: master

dev:
  NAMESPACE: "{{ ninja_board_dev_namespace }}"
  DISPLAY_NAME: "Ninja Board - Dev"
  APP_NAME: "{{ app_name }}"

prod:
  NAMESPACE: "{{ ninja_board_prod_namespace }}"
  DISPLAY_NAME: "Ninja Board - Prod"
