---
openshift_cluster_content:
  - object: projectrequest
    content:
      - name: ninja-board-project-dev
        template: "{{ inventory_dir }}/../../.openshift/projects/project.yml"
        action: create
        params_from_vars: "{{ dev }}"
        tags:
          - projects-{{ ninja_board_dev_namespace }}
          - projects
      - name: ninja-board-project
        template: "{{ inventory_dir }}/../../.openshift/projects/project.yml"
        action: create
        params_from_vars: "{{ prod }}"
        tags:
          - projects-{{ ninja_board_prod_namespace }}
          - projects
  - object: cicd
    content:
      - name: Deploy Jenkins Master
        template: "{{ inventory_dir }}/../../.openshift/templates/jenkins-ephemeral.yml"
        namespace: "{{ ninja_board_dev_namespace }}"
        params_from_vars:
          MEMORY_LIMIT: 2Gi
        tags:
          - projects-{{ ninja_board_dev_namespace }}
          - cicd
  - object: builds
    content:
      - name: "build-ninja-board"
        template: "{{ inventory_dir }}/../../.openshift/templates/ninja-board-build.yml"
        params_from_vars:
          SOURCE_REPOSITORY_URL: "{{ source_repo }}"
          SOURCE_REPOSITORY_REF: "{{ source_ref }}"
        namespace: "{{ ninja_board_dev_namespace }}"
        tags:
          - projects-{{ ninja_board_dev_namespace }}
          - builds
  - object: deployments
    content:
      - name: "deploy-ninja-board"
        template: "{{ inventory_dir }}/../../.openshift/templates/ninja-board-deployment.yml"
        params_from_vars:
          GITHUB_API_TOKEN: "{{ github_api_token }}"
          TRELLO_API_TOKEN: "{{ trello_api_token }}"
          TRELLO_API_KEY: "{{ trello_api_key }}"
          GITLAB_API_TOKEN: "{{ gitlab_api_token }}"
          GD_CREDENTIALS: "{{ gd_credentials }}"
          XGRAPHS_PROXY: "{{ xgraphs_proxy }}"
          USERS_LDAP_PROVIDER: "{{ users_ldap_provider }}"
        namespace: "{{ ninja_board_dev_namespace }}"
        tags:
          - projects-{{ ninja_board_dev_namespace }}
          - deployments
