openapi: 3.0.2
info:
  title: Giveback Ninja
  version: 2.0.0
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'
paths:
  /user:
    post:
      requestBody:
        content:
          application/json: {}
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: Creates a user within the system.
      summary: Registers a new user in the system.
  /scorecard:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Scorecard'
          description: Returns a list of all user scorecards.
      summary: Get all user scorecards.
  '/scorecard/{username}':
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scorecard'
              examples:
                super_ninja:
                  value: |-
                    username: super_ninja
                    level: black
                    total: 248
                    pointsToNextLevel: 0
                    nextLevel: ''
                    pointMap:
                        githubReviewedPullRequests: 24
                        githubClosedIssues: 0
                        servicesSupportMergeRequests: 0
                        servicesSupportClosedIssues: 0
                        servicesSupportReviewedMergeRequests: 0
                        githubPullRequests: 34
                        gitlabMergeRequests: 43
                        trelloCardsClosed: 23
                        thoughtLeadershipCardsClosed: 1
                        servicesSupportCardsClosed: 10
          description: Get Scorecard Info
      summary: Get UserScorecard info for a specific user.
    parameters:
    - name: username
      description: The unique name of a specific user.
      schema:
        type: string
      in: path
      required: true
  '/scorecard/{username}/{pool}':
    post:
      requestBody:
        content:
          text/plain:
            schema:
              type: integer
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Scorecard'
          description: Pool for provided username was incremented successfully.
    parameters:
    - name: username
      description: The unique name of the user.
      schema:
        type: string
      in: path
      required: true
    - name: pool
      description: The pool to increment. The pool will be created if not already defined.
      schema:
        type: string
      in: path
      required: true
components:
  schemas:
    User:
      title: Root Type for User
      description: ''
      type: object
      properties:
        displayName:
          description: >-
            The name displayed to all users of the system. Typically the users first and last
            name.
          type: string
        username:
          description: The user's Red Hat Kerberos ID.
          type: string
        githubUsername:
          description: The user's Github username.
          type: string
        trelloUsername:
          description: The user's Trello username.
          type: string
        email:
          description: The Red Hat email associated with the user.
          type: string
      example:
        displayName: Super Ninja
        username: super_ninja
        githubUsername: super_ninja
        trelloUsername: super_ninja
        email: super_ninja@redhat.com
    Scorecard:
      title: Root Type for UserScorecard
      description: All stats around a user that are used to calculate Ninja Belt level.
      required:
      - username
      type: object
      properties:
        username:
          description: The unique user id.
          type: string
        level:
          description: The current level of the ninja
          type: string
        total:
          description: Total Accumulated Point
          type: integer
        pointsToNextLevel:
          description: |
            The number of points needed to achieve the next level. 0 indicates
            that there is no higher level.
          type: integer
        nextLevel:
          description: |
            The level that can be reached next. An empty string indicates that 
            the current level is the highest.
          type: string
        pointMap:
          description: list of all accumulated points.
          type: object
          additionalProperties:
            type: integer
      example:
        username: super_ninja
        level: black
        total: 248
        pointsToNextLevel: 0
        nextLevel: ''
        pointMap:
          githubReviewedPullRequests: 24
          githubClosedIssues: 0
          servicesSupportMergeRequests: 0
          servicesSupportClosedIssues: 0
          servicesSupportReviewedMergeRequests: 0
          githubPullRequests: 34
          gitlabMergeRequests: 43
          trelloCardsClosed: 23
          thoughtLeadershipCardsClosed: 1
          servicesSupportCardsClosed: 10